FROM postgres:latest

MAINTAINER Leonardo Tegon <ltegon93@gmail.com>

COPY ./config/database/create_user.sh /docker-entrypoint-initdb.d/10-create_user.sh
COPY ./config/database/create_db.sh /docker-entrypoint-initdb.d/20-create_db.sh
COPY ./config/database/create_uuid_extension.sh /docker-entrypoint-initdb.d/30-create_uuid_extension.sh
